version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: smartcampus_db
    environment:
      POSTGRES_DB: smartcampus
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass123
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartuser -d smartcampus"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: smartcampus_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: smartcampus
      DB_USER: smartuser
      DB_PASS: smartpass123
      JWT_SECRET: SmartCampusUTA_SecretKey_2024
      PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: smartcampus_frontend
    ports:
      - "8090:80"    # HTTP  → redirige a HTTPS
      - "8443:443"   # HTTPS → acceso principal
    depends_on:
      - backend
    restart: always

volumes:
  pg_data:
